/*
 * Simple API
 * Simple API Description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.andrestefanov.android.nearbuy.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * RequestArticleStatusDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-03-22T15:06:40.738994+01:00[Europe/Berlin]")
public class RequestArticleStatusDto {
  public static final String SERIALIZED_NAME_ARTICLE_DONE = "articleDone";
  @SerializedName(SERIALIZED_NAME_ARTICLE_DONE)
  private Boolean articleDone;


  public RequestArticleStatusDto articleDone(Boolean articleDone) {
    
    this.articleDone = articleDone;
    return this;
  }

   /**
   * Get articleDone
   * @return articleDone
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getArticleDone() {
    return articleDone;
  }


  public void setArticleDone(Boolean articleDone) {
    this.articleDone = articleDone;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestArticleStatusDto requestArticleStatusDto = (RequestArticleStatusDto) o;
    return Objects.equals(this.articleDone, requestArticleStatusDto.articleDone);
  }

  @Override
  public int hashCode() {
    return Objects.hash(articleDone);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestArticleStatusDto {\n");
    sb.append("    articleDone: ").append(toIndentedString(articleDone)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

