/*
 * Nexd API
 * Swagger API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package app.nexd.android.api.model;

import java.util.Objects;
import java.util.Arrays;
import app.nexd.android.api.model.User;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.Date;

/**
 * Call
 */

public class Call {
  public static final String SERIALIZED_NAME_CONVERTED_HELP_REQUEST_ID = "convertedHelpRequestId";
  @SerializedName(SERIALIZED_NAME_CONVERTED_HELP_REQUEST_ID)
  private Long convertedHelpRequestId;

  public static final String SERIALIZED_NAME_SID = "sid";
  @SerializedName(SERIALIZED_NAME_SID)
  private String sid;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private Date createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  private Date updatedAt;

  public static final String SERIALIZED_NAME_RECORDING_URL = "recordingUrl";
  @SerializedName(SERIALIZED_NAME_RECORDING_URL)
  private String recordingUrl;

  public static final String SERIALIZED_NAME_PHONE_NUMBER = "phoneNumber";
  @SerializedName(SERIALIZED_NAME_PHONE_NUMBER)
  private String phoneNumber;

  public static final String SERIALIZED_NAME_COUNTRY = "country";
  @SerializedName(SERIALIZED_NAME_COUNTRY)
  private String country;

  public static final String SERIALIZED_NAME_ZIP = "zip";
  @SerializedName(SERIALIZED_NAME_ZIP)
  private String zip;

  public static final String SERIALIZED_NAME_CITY = "city";
  @SerializedName(SERIALIZED_NAME_CITY)
  private String city;

  public static final String SERIALIZED_NAME_CONVERTER_ID = "converterId";
  @SerializedName(SERIALIZED_NAME_CONVERTER_ID)
  private String converterId;

  public static final String SERIALIZED_NAME_CONVERTER = "converter";
  @SerializedName(SERIALIZED_NAME_CONVERTER)
  private User converter;


  public Call convertedHelpRequestId(Long convertedHelpRequestId) {
    
    this.convertedHelpRequestId = convertedHelpRequestId;
    return this;
  }

   /**
   * Get convertedHelpRequestId
   * @return convertedHelpRequestId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getConvertedHelpRequestId() {
    return convertedHelpRequestId;
  }


  public void setConvertedHelpRequestId(Long convertedHelpRequestId) {
    this.convertedHelpRequestId = convertedHelpRequestId;
  }


  public Call sid(String sid) {
    
    this.sid = sid;
    return this;
  }

   /**
   * Get sid
   * @return sid
  **/
  @ApiModelProperty(required = true, value = "")

  public String getSid() {
    return sid;
  }


  public void setSid(String sid) {
    this.sid = sid;
  }


  public Call createdAt(Date createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @ApiModelProperty(required = true, value = "")

  public Date getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(Date createdAt) {
    this.createdAt = createdAt;
  }


  public Call updatedAt(Date updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @ApiModelProperty(required = true, value = "")

  public Date getUpdatedAt() {
    return updatedAt;
  }


  public void setUpdatedAt(Date updatedAt) {
    this.updatedAt = updatedAt;
  }


  public Call recordingUrl(String recordingUrl) {
    
    this.recordingUrl = recordingUrl;
    return this;
  }

   /**
   * Get recordingUrl
   * @return recordingUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getRecordingUrl() {
    return recordingUrl;
  }


  public void setRecordingUrl(String recordingUrl) {
    this.recordingUrl = recordingUrl;
  }


  public Call phoneNumber(String phoneNumber) {
    
    this.phoneNumber = phoneNumber;
    return this;
  }

   /**
   * Get phoneNumber
   * @return phoneNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPhoneNumber() {
    return phoneNumber;
  }


  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }


  public Call country(String country) {
    
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCountry() {
    return country;
  }


  public void setCountry(String country) {
    this.country = country;
  }


  public Call zip(String zip) {
    
    this.zip = zip;
    return this;
  }

   /**
   * Get zip
   * @return zip
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getZip() {
    return zip;
  }


  public void setZip(String zip) {
    this.zip = zip;
  }


  public Call city(String city) {
    
    this.city = city;
    return this;
  }

   /**
   * Get city
   * @return city
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCity() {
    return city;
  }


  public void setCity(String city) {
    this.city = city;
  }


  public Call converterId(String converterId) {
    
    this.converterId = converterId;
    return this;
  }

   /**
   * Get converterId
   * @return converterId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getConverterId() {
    return converterId;
  }


  public void setConverterId(String converterId) {
    this.converterId = converterId;
  }


  public Call converter(User converter) {
    
    this.converter = converter;
    return this;
  }

   /**
   * Get converter
   * @return converter
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public User getConverter() {
    return converter;
  }


  public void setConverter(User converter) {
    this.converter = converter;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Call call = (Call) o;
    return Objects.equals(this.convertedHelpRequestId, call.convertedHelpRequestId) &&
        Objects.equals(this.sid, call.sid) &&
        Objects.equals(this.createdAt, call.createdAt) &&
        Objects.equals(this.updatedAt, call.updatedAt) &&
        Objects.equals(this.recordingUrl, call.recordingUrl) &&
        Objects.equals(this.phoneNumber, call.phoneNumber) &&
        Objects.equals(this.country, call.country) &&
        Objects.equals(this.zip, call.zip) &&
        Objects.equals(this.city, call.city) &&
        Objects.equals(this.converterId, call.converterId) &&
        Objects.equals(this.converter, call.converter);
  }

  @Override
  public int hashCode() {
    return Objects.hash(convertedHelpRequestId, sid, createdAt, updatedAt, recordingUrl, phoneNumber, country, zip, city, converterId, converter);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Call {\n");
    sb.append("    convertedHelpRequestId: ").append(toIndentedString(convertedHelpRequestId)).append("\n");
    sb.append("    sid: ").append(toIndentedString(sid)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    recordingUrl: ").append(toIndentedString(recordingUrl)).append("\n");
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    zip: ").append(toIndentedString(zip)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    converterId: ").append(toIndentedString(converterId)).append("\n");
    sb.append("    converter: ").append(toIndentedString(converter)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

