/*
 * Nexd API
 * Swagger API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package app.nexd.android.api.model;

import java.util.Objects;
import java.util.Arrays;
import app.nexd.android.api.model.HelpRequest;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.Date;

/**
 * Call
 */

public class Call {
  public static final String SERIALIZED_NAME_SID = "sid";
  @SerializedName(SERIALIZED_NAME_SID)
  private String sid;

  public static final String SERIALIZED_NAME_CREATED = "created";
  @SerializedName(SERIALIZED_NAME_CREATED)
  private Date created;

  public static final String SERIALIZED_NAME_RECORD_URL = "recordUrl";
  @SerializedName(SERIALIZED_NAME_RECORD_URL)
  private String recordUrl;

  public static final String SERIALIZED_NAME_TRANSCRIPTION_URL = "transcriptionUrl";
  @SerializedName(SERIALIZED_NAME_TRANSCRIPTION_URL)
  private String transcriptionUrl;

  public static final String SERIALIZED_NAME_CONVERTED_HELP_REQUEST = "convertedHelpRequest";
  @SerializedName(SERIALIZED_NAME_CONVERTED_HELP_REQUEST)
  private HelpRequest convertedHelpRequest;

  public static final String SERIALIZED_NAME_PHONE_NUMBER = "phoneNumber";
  @SerializedName(SERIALIZED_NAME_PHONE_NUMBER)
  private String phoneNumber;

  public static final String SERIALIZED_NAME_COUNTRY = "country";
  @SerializedName(SERIALIZED_NAME_COUNTRY)
  private String country;

  public static final String SERIALIZED_NAME_ZIP = "zip";
  @SerializedName(SERIALIZED_NAME_ZIP)
  private String zip;

  public static final String SERIALIZED_NAME_CITY = "city";
  @SerializedName(SERIALIZED_NAME_CITY)
  private String city;


  public Call sid(String sid) {
    
    this.sid = sid;
    return this;
  }

   /**
   * Get sid
   * @return sid
  **/
  @ApiModelProperty(required = true, value = "")

  public String getSid() {
    return sid;
  }


  public void setSid(String sid) {
    this.sid = sid;
  }


  public Call created(Date created) {
    
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @ApiModelProperty(required = true, value = "")

  public Date getCreated() {
    return created;
  }


  public void setCreated(Date created) {
    this.created = created;
  }


  public Call recordUrl(String recordUrl) {
    
    this.recordUrl = recordUrl;
    return this;
  }

   /**
   * Get recordUrl
   * @return recordUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getRecordUrl() {
    return recordUrl;
  }


  public void setRecordUrl(String recordUrl) {
    this.recordUrl = recordUrl;
  }


  public Call transcriptionUrl(String transcriptionUrl) {
    
    this.transcriptionUrl = transcriptionUrl;
    return this;
  }

   /**
   * Get transcriptionUrl
   * @return transcriptionUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTranscriptionUrl() {
    return transcriptionUrl;
  }


  public void setTranscriptionUrl(String transcriptionUrl) {
    this.transcriptionUrl = transcriptionUrl;
  }


  public Call convertedHelpRequest(HelpRequest convertedHelpRequest) {
    
    this.convertedHelpRequest = convertedHelpRequest;
    return this;
  }

   /**
   * Get convertedHelpRequest
   * @return convertedHelpRequest
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public HelpRequest getConvertedHelpRequest() {
    return convertedHelpRequest;
  }


  public void setConvertedHelpRequest(HelpRequest convertedHelpRequest) {
    this.convertedHelpRequest = convertedHelpRequest;
  }


  public Call phoneNumber(String phoneNumber) {
    
    this.phoneNumber = phoneNumber;
    return this;
  }

   /**
   * Get phoneNumber
   * @return phoneNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPhoneNumber() {
    return phoneNumber;
  }


  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }


  public Call country(String country) {
    
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCountry() {
    return country;
  }


  public void setCountry(String country) {
    this.country = country;
  }


  public Call zip(String zip) {
    
    this.zip = zip;
    return this;
  }

   /**
   * Get zip
   * @return zip
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getZip() {
    return zip;
  }


  public void setZip(String zip) {
    this.zip = zip;
  }


  public Call city(String city) {
    
    this.city = city;
    return this;
  }

   /**
   * Get city
   * @return city
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCity() {
    return city;
  }


  public void setCity(String city) {
    this.city = city;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Call call = (Call) o;
    return Objects.equals(this.sid, call.sid) &&
        Objects.equals(this.created, call.created) &&
        Objects.equals(this.recordUrl, call.recordUrl) &&
        Objects.equals(this.transcriptionUrl, call.transcriptionUrl) &&
        Objects.equals(this.convertedHelpRequest, call.convertedHelpRequest) &&
        Objects.equals(this.phoneNumber, call.phoneNumber) &&
        Objects.equals(this.country, call.country) &&
        Objects.equals(this.zip, call.zip) &&
        Objects.equals(this.city, call.city);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sid, created, recordUrl, transcriptionUrl, convertedHelpRequest, phoneNumber, country, zip, city);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Call {\n");
    sb.append("    sid: ").append(toIndentedString(sid)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    recordUrl: ").append(toIndentedString(recordUrl)).append("\n");
    sb.append("    transcriptionUrl: ").append(toIndentedString(transcriptionUrl)).append("\n");
    sb.append("    convertedHelpRequest: ").append(toIndentedString(convertedHelpRequest)).append("\n");
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    zip: ").append(toIndentedString(zip)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

