/*
 * Nexd API
 * Swagger API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package app.nexd.android.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CreateHelpRequestArticleDto
 */

public class CreateHelpRequestArticleDto {
  public static final String SERIALIZED_NAME_ARTICLE_ID = "articleId";
  @SerializedName(SERIALIZED_NAME_ARTICLE_ID)
  private Long articleId;

  public static final String SERIALIZED_NAME_ARTICLE_COUNT = "articleCount";
  @SerializedName(SERIALIZED_NAME_ARTICLE_COUNT)
  private Long articleCount;


  public CreateHelpRequestArticleDto articleId(Long articleId) {
    
    this.articleId = articleId;
    return this;
  }

   /**
   * Article ID received from the article list
   * @return articleId
  **/
  @ApiModelProperty(required = true, value = "Article ID received from the article list")

  public Long getArticleId() {
    return articleId;
  }


  public void setArticleId(Long articleId) {
    this.articleId = articleId;
  }


  public CreateHelpRequestArticleDto articleCount(Long articleCount) {
    
    this.articleCount = articleCount;
    return this;
  }

   /**
   * Number of items
   * @return articleCount
  **/
  @ApiModelProperty(required = true, value = "Number of items")

  public Long getArticleCount() {
    return articleCount;
  }


  public void setArticleCount(Long articleCount) {
    this.articleCount = articleCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateHelpRequestArticleDto createHelpRequestArticleDto = (CreateHelpRequestArticleDto) o;
    return Objects.equals(this.articleId, createHelpRequestArticleDto.articleId) &&
        Objects.equals(this.articleCount, createHelpRequestArticleDto.articleCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(articleId, articleCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateHelpRequestArticleDto {\n");
    sb.append("    articleId: ").append(toIndentedString(articleId)).append("\n");
    sb.append("    articleCount: ").append(toIndentedString(articleCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

