/*
 * Nexd API
 * Swagger API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package app.nexd.android.api.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * EmailPasswordResetDto
 */

public class EmailPasswordResetDto {
  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  private String email;

  public static final String SERIALIZED_NAME_PASSWORD_RESET_TOKEN = "passwordResetToken";
  @SerializedName(SERIALIZED_NAME_PASSWORD_RESET_TOKEN)
  private String passwordResetToken;

  public static final String SERIALIZED_NAME_PASSWORD = "password";
  @SerializedName(SERIALIZED_NAME_PASSWORD)
  private String password;


  public EmailPasswordResetDto email(String email) {
    
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @ApiModelProperty(example = "test@test.com", required = true, value = "")

  public String getEmail() {
    return email;
  }


  public void setEmail(String email) {
    this.email = email;
  }


  public EmailPasswordResetDto passwordResetToken(String passwordResetToken) {
    
    this.passwordResetToken = passwordResetToken;
    return this;
  }

   /**
   * Get passwordResetToken
   * @return passwordResetToken
  **/
  @ApiModelProperty(required = true, value = "")

  public String getPasswordResetToken() {
    return passwordResetToken;
  }


  public void setPasswordResetToken(String passwordResetToken) {
    this.passwordResetToken = passwordResetToken;
  }


  public EmailPasswordResetDto password(String password) {
    
    this.password = password;
    return this;
  }

   /**
   * Get password
   * @return password
  **/
  @ApiModelProperty(required = true, value = "")

  public String getPassword() {
    return password;
  }


  public void setPassword(String password) {
    this.password = password;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmailPasswordResetDto emailPasswordResetDto = (EmailPasswordResetDto) o;
    return Objects.equals(this.email, emailPasswordResetDto.email) &&
        Objects.equals(this.passwordResetToken, emailPasswordResetDto.passwordResetToken) &&
        Objects.equals(this.password, emailPasswordResetDto.password);
  }

  @Override
  public int hashCode() {
    return Objects.hash(email, passwordResetToken, password);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmailPasswordResetDto {\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    passwordResetToken: ").append(toIndentedString(passwordResetToken)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

