/*
 * Nexd API
 * Swagger API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package app.nexd.android.api.model;

import java.util.Objects;
import java.util.Arrays;
import app.nexd.android.api.model.Article;
import app.nexd.android.api.model.HelpRequest;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * HelpRequestArticle
 */

public class HelpRequestArticle {
  public static final String SERIALIZED_NAME_ARTICLE_ID = "articleId";
  @SerializedName(SERIALIZED_NAME_ARTICLE_ID)
  private Integer articleId;

  public static final String SERIALIZED_NAME_ARTICLE_COUNT = "articleCount";
  @SerializedName(SERIALIZED_NAME_ARTICLE_COUNT)
  private Integer articleCount;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_ARTICLE = "article";
  @SerializedName(SERIALIZED_NAME_ARTICLE)
  private Article article;

  public static final String SERIALIZED_NAME_ARTICLE_DONE = "articleDone";
  @SerializedName(SERIALIZED_NAME_ARTICLE_DONE)
  private Boolean articleDone;

  public static final String SERIALIZED_NAME_HELP_REQUEST = "helpRequest";
  @SerializedName(SERIALIZED_NAME_HELP_REQUEST)
  private HelpRequest helpRequest;


  public HelpRequestArticle articleId(Integer articleId) {
    
    this.articleId = articleId;
    return this;
  }

   /**
   * Get articleId
   * @return articleId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getArticleId() {
    return articleId;
  }


  public void setArticleId(Integer articleId) {
    this.articleId = articleId;
  }


  public HelpRequestArticle articleCount(Integer articleCount) {
    
    this.articleCount = articleCount;
    return this;
  }

   /**
   * Get articleCount
   * @return articleCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getArticleCount() {
    return articleCount;
  }


  public void setArticleCount(Integer articleCount) {
    this.articleCount = articleCount;
  }


  public HelpRequestArticle id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getId() {
    return id;
  }


  public void setId(Integer id) {
    this.id = id;
  }


  public HelpRequestArticle article(Article article) {
    
    this.article = article;
    return this;
  }

   /**
   * Get article
   * @return article
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Article getArticle() {
    return article;
  }


  public void setArticle(Article article) {
    this.article = article;
  }


  public HelpRequestArticle articleDone(Boolean articleDone) {
    
    this.articleDone = articleDone;
    return this;
  }

   /**
   * Get articleDone
   * @return articleDone
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getArticleDone() {
    return articleDone;
  }


  public void setArticleDone(Boolean articleDone) {
    this.articleDone = articleDone;
  }


  public HelpRequestArticle helpRequest(HelpRequest helpRequest) {
    
    this.helpRequest = helpRequest;
    return this;
  }

   /**
   * Get helpRequest
   * @return helpRequest
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public HelpRequest getHelpRequest() {
    return helpRequest;
  }


  public void setHelpRequest(HelpRequest helpRequest) {
    this.helpRequest = helpRequest;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HelpRequestArticle helpRequestArticle = (HelpRequestArticle) o;
    return Objects.equals(this.articleId, helpRequestArticle.articleId) &&
        Objects.equals(this.articleCount, helpRequestArticle.articleCount) &&
        Objects.equals(this.id, helpRequestArticle.id) &&
        Objects.equals(this.article, helpRequestArticle.article) &&
        Objects.equals(this.articleDone, helpRequestArticle.articleDone) &&
        Objects.equals(this.helpRequest, helpRequestArticle.helpRequest);
  }

  @Override
  public int hashCode() {
    return Objects.hash(articleId, articleCount, id, article, articleDone, helpRequest);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HelpRequestArticle {\n");
    sb.append("    articleId: ").append(toIndentedString(articleId)).append("\n");
    sb.append("    articleCount: ").append(toIndentedString(articleCount)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    article: ").append(toIndentedString(article)).append("\n");
    sb.append("    articleDone: ").append(toIndentedString(articleDone)).append("\n");
    sb.append("    helpRequest: ").append(toIndentedString(helpRequest)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

