/*
 * Nexd API
 * Swagger API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package app.nexd.android.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * HelpListCreateDto
 */

public class HelpListCreateDto {
  public static final String SERIALIZED_NAME_HELP_REQUESTS_IDS = "helpRequestsIds";
  @SerializedName(SERIALIZED_NAME_HELP_REQUESTS_IDS)
  private List<Integer> helpRequestsIds = null;

  /**
   * Gets or Sets status
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    ACTIVE("active"),
    
    CANCELED("canceled"),
    
    COMPLETED("completed");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StatusEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private StatusEnum status = StatusEnum.ACTIVE;


  public HelpListCreateDto helpRequestsIds(List<Integer> helpRequestsIds) {
    
    this.helpRequestsIds = helpRequestsIds;
    return this;
  }

  public HelpListCreateDto addHelpRequestsIdsItem(Integer helpRequestsIdsItem) {
    if (this.helpRequestsIds == null) {
      this.helpRequestsIds = new ArrayList<Integer>();
    }
    this.helpRequestsIds.add(helpRequestsIdsItem);
    return this;
  }

   /**
   * List of help request IDs
   * @return helpRequestsIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List of help request IDs")

  public List<Integer> getHelpRequestsIds() {
    return helpRequestsIds;
  }


  public void setHelpRequestsIds(List<Integer> helpRequestsIds) {
    this.helpRequestsIds = helpRequestsIds;
  }


  public HelpListCreateDto status(StatusEnum status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public StatusEnum getStatus() {
    return status;
  }


  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HelpListCreateDto helpListCreateDto = (HelpListCreateDto) o;
    return Objects.equals(this.helpRequestsIds, helpListCreateDto.helpRequestsIds) &&
        Objects.equals(this.status, helpListCreateDto.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(helpRequestsIds, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HelpListCreateDto {\n");
    sb.append("    helpRequestsIds: ").append(toIndentedString(helpRequestsIds)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

