/*
 * Nexd API
 * Swagger API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package app.nexd.android.api.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * HelpRequestArticle
 */

public class HelpRequestArticle {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Long id;

  public static final String SERIALIZED_NAME_ARTICLE_ID = "articleId";
  @SerializedName(SERIALIZED_NAME_ARTICLE_ID)
  private Long articleId;

  public static final String SERIALIZED_NAME_UNIT_ID = "unitId";
  @SerializedName(SERIALIZED_NAME_UNIT_ID)
  private Long unitId;

  public static final String SERIALIZED_NAME_ARTICLE_COUNT = "articleCount";
  @SerializedName(SERIALIZED_NAME_ARTICLE_COUNT)
  private Long articleCount;

  public static final String SERIALIZED_NAME_ARTICLE = "article";
  @SerializedName(SERIALIZED_NAME_ARTICLE)
  private Article article;

  public static final String SERIALIZED_NAME_UNIT = "unit";
  @SerializedName(SERIALIZED_NAME_UNIT)
  private Unit unit;

  public static final String SERIALIZED_NAME_ARTICLE_DONE = "articleDone";
  @SerializedName(SERIALIZED_NAME_ARTICLE_DONE)
  private Boolean articleDone;

  public static final String SERIALIZED_NAME_HELP_REQUEST = "helpRequest";
  @SerializedName(SERIALIZED_NAME_HELP_REQUEST)
  private HelpRequest helpRequest;


  public HelpRequestArticle id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getId() {
    return id;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public HelpRequestArticle articleId(Long articleId) {
    
    this.articleId = articleId;
    return this;
  }

   /**
   * Get articleId
   * @return articleId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getArticleId() {
    return articleId;
  }


  public void setArticleId(Long articleId) {
    this.articleId = articleId;
  }


  public HelpRequestArticle unitId(Long unitId) {
    
    this.unitId = unitId;
    return this;
  }

   /**
   * Get unitId
   * @return unitId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getUnitId() {
    return unitId;
  }


  public void setUnitId(Long unitId) {
    this.unitId = unitId;
  }


  public HelpRequestArticle articleCount(Long articleCount) {
    
    this.articleCount = articleCount;
    return this;
  }

   /**
   * Get articleCount
   * @return articleCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getArticleCount() {
    return articleCount;
  }


  public void setArticleCount(Long articleCount) {
    this.articleCount = articleCount;
  }


  public HelpRequestArticle article(Article article) {
    
    this.article = article;
    return this;
  }

   /**
   * Get article
   * @return article
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Article getArticle() {
    return article;
  }


  public void setArticle(Article article) {
    this.article = article;
  }


  public HelpRequestArticle unit(Unit unit) {
    
    this.unit = unit;
    return this;
  }

   /**
   * Get unit
   * @return unit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Unit getUnit() {
    return unit;
  }


  public void setUnit(Unit unit) {
    this.unit = unit;
  }


  public HelpRequestArticle articleDone(Boolean articleDone) {
    
    this.articleDone = articleDone;
    return this;
  }

   /**
   * Get articleDone
   * @return articleDone
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getArticleDone() {
    return articleDone;
  }


  public void setArticleDone(Boolean articleDone) {
    this.articleDone = articleDone;
  }


  public HelpRequestArticle helpRequest(HelpRequest helpRequest) {
    
    this.helpRequest = helpRequest;
    return this;
  }

   /**
   * Get helpRequest
   * @return helpRequest
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public HelpRequest getHelpRequest() {
    return helpRequest;
  }


  public void setHelpRequest(HelpRequest helpRequest) {
    this.helpRequest = helpRequest;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HelpRequestArticle helpRequestArticle = (HelpRequestArticle) o;
    return Objects.equals(this.id, helpRequestArticle.id) &&
        Objects.equals(this.articleId, helpRequestArticle.articleId) &&
        Objects.equals(this.unitId, helpRequestArticle.unitId) &&
        Objects.equals(this.articleCount, helpRequestArticle.articleCount) &&
        Objects.equals(this.article, helpRequestArticle.article) &&
        Objects.equals(this.unit, helpRequestArticle.unit) &&
        Objects.equals(this.articleDone, helpRequestArticle.articleDone) &&
        Objects.equals(this.helpRequest, helpRequestArticle.helpRequest);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, articleId, unitId, articleCount, article, unit, articleDone, helpRequest);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HelpRequestArticle {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    articleId: ").append(toIndentedString(articleId)).append("\n");
    sb.append("    unitId: ").append(toIndentedString(unitId)).append("\n");
    sb.append("    articleCount: ").append(toIndentedString(articleCount)).append("\n");
    sb.append("    article: ").append(toIndentedString(article)).append("\n");
    sb.append("    unit: ").append(toIndentedString(unit)).append("\n");
    sb.append("    articleDone: ").append(toIndentedString(articleDone)).append("\n");
    sb.append("    helpRequest: ").append(toIndentedString(helpRequest)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

