/*
 * Simple API
 * Simple API Description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package app.nexd.android.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * RequestArticle
 */

public class RequestArticle {
  public static final String SERIALIZED_NAME_ARTICLE_ID = "articleId";
  @SerializedName(SERIALIZED_NAME_ARTICLE_ID)
  private BigDecimal articleId;

  public static final String SERIALIZED_NAME_ARTICLE_COUNT = "articleCount";
  @SerializedName(SERIALIZED_NAME_ARTICLE_COUNT)
  private BigDecimal articleCount;

  public static final String SERIALIZED_NAME_ARTICLE_DONE = "articleDone";
  @SerializedName(SERIALIZED_NAME_ARTICLE_DONE)
  private Boolean articleDone;


  public RequestArticle articleId(BigDecimal articleId) {
    
    this.articleId = articleId;
    return this;
  }

   /**
   * Get articleId
   * @return articleId
  **/
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getArticleId() {
    return articleId;
  }


  public void setArticleId(BigDecimal articleId) {
    this.articleId = articleId;
  }


  public RequestArticle articleCount(BigDecimal articleCount) {
    
    this.articleCount = articleCount;
    return this;
  }

   /**
   * Get articleCount
   * @return articleCount
  **/
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getArticleCount() {
    return articleCount;
  }


  public void setArticleCount(BigDecimal articleCount) {
    this.articleCount = articleCount;
  }


  public RequestArticle articleDone(Boolean articleDone) {
    
    this.articleDone = articleDone;
    return this;
  }

   /**
   * Get articleDone
   * @return articleDone
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getArticleDone() {
    return articleDone;
  }


  public void setArticleDone(Boolean articleDone) {
    this.articleDone = articleDone;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestArticle requestArticle = (RequestArticle) o;
    return Objects.equals(this.articleId, requestArticle.articleId) &&
        Objects.equals(this.articleCount, requestArticle.articleCount) &&
        Objects.equals(this.articleDone, requestArticle.articleDone);
  }

  @Override
  public int hashCode() {
    return Objects.hash(articleId, articleCount, articleDone);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestArticle {\n");
    sb.append("    articleId: ").append(toIndentedString(articleId)).append("\n");
    sb.append("    articleCount: ").append(toIndentedString(articleCount)).append("\n");
    sb.append("    articleDone: ").append(toIndentedString(articleDone)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

