/*
 * Nexd API
 * Swagger API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package app.nexd.android.api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * Unit
 */

public class Unit {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Long id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_NAME_SHORT = "nameShort";
  @SerializedName(SERIALIZED_NAME_NAME_SHORT)
  private String nameShort;

  /**
   * Language key of this unit
   */
  @JsonAdapter(LanguageEnum.Adapter.class)
  public enum LanguageEnum {
    DE("de"),
    
    EN("en");

    private String value;

    LanguageEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static LanguageEnum fromValue(String value) {
      for (LanguageEnum b : LanguageEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<LanguageEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final LanguageEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public LanguageEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return LanguageEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_LANGUAGE = "language";
  @SerializedName(SERIALIZED_NAME_LANGUAGE)
  private LanguageEnum language;

  public static final String SERIALIZED_NAME_DEFAULT_ORDER = "defaultOrder";
  @SerializedName(SERIALIZED_NAME_DEFAULT_ORDER)
  private Long defaultOrder;


  public Unit id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Auto-incremented ID of a unit.
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Auto-incremented ID of a unit.")

  public Long getId() {
    return id;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public Unit name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Name of the unit
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Name of the unit")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public Unit nameShort(String nameShort) {
    
    this.nameShort = nameShort;
    return this;
  }

   /**
   * Abbreviated name of the unit
   * @return nameShort
  **/
  @ApiModelProperty(required = true, value = "Abbreviated name of the unit")

  public String getNameShort() {
    return nameShort;
  }


  public void setNameShort(String nameShort) {
    this.nameShort = nameShort;
  }


  public Unit language(LanguageEnum language) {
    
    this.language = language;
    return this;
  }

   /**
   * Language key of this unit
   * @return language
  **/
  @ApiModelProperty(required = true, value = "Language key of this unit")

  public LanguageEnum getLanguage() {
    return language;
  }


  public void setLanguage(LanguageEnum language) {
    this.language = language;
  }


  public Unit defaultOrder(Long defaultOrder) {
    
    this.defaultOrder = defaultOrder;
    return this;
  }

   /**
   * Some default ordering, in case there is no automatic ordering for an article, no need in the frontend.
   * @return defaultOrder
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Some default ordering, in case there is no automatic ordering for an article, no need in the frontend.")

  public Long getDefaultOrder() {
    return defaultOrder;
  }


  public void setDefaultOrder(Long defaultOrder) {
    this.defaultOrder = defaultOrder;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Unit unit = (Unit) o;
    return Objects.equals(this.id, unit.id) &&
        Objects.equals(this.name, unit.name) &&
        Objects.equals(this.nameShort, unit.nameShort) &&
        Objects.equals(this.language, unit.language) &&
        Objects.equals(this.defaultOrder, unit.defaultOrder);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, nameShort, language, defaultOrder);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Unit {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    nameShort: ").append(toIndentedString(nameShort)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    defaultOrder: ").append(toIndentedString(defaultOrder)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

