/*
 * Simple API
 * Simple API Description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.andrestefanov.android.nearbuy.api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for RequestArticleStatusDto
 */
public class RequestArticleStatusDtoTest {
    private final RequestArticleStatusDto model = new RequestArticleStatusDto();

    /**
     * Model tests for RequestArticleStatusDto
     */
    @Test
    public void testRequestArticleStatusDto() {
        // TODO: test RequestArticleStatusDto
    }

    /**
     * Test the property 'articleDone'
     */
    @Test
    public void articleDoneTest() {
        // TODO: test articleDone
    }

}
