/*
 * Simple API
 * Simple API Description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.andrestefanov.android.nearbuy.api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for RequestArticle
 */
public class RequestArticleTest {
    private final RequestArticle model = new RequestArticle();

    /**
     * Model tests for RequestArticle
     */
    @Test
    public void testRequestArticle() {
        // TODO: test RequestArticle
    }

    /**
     * Test the property 'articleId'
     */
    @Test
    public void articleIdTest() {
        // TODO: test articleId
    }

    /**
     * Test the property 'articleCount'
     */
    @Test
    public void articleCountTest() {
        // TODO: test articleCount
    }

    /**
     * Test the property 'articleDone'
     */
    @Test
    public void articleDoneTest() {
        // TODO: test articleDone
    }

}
